### ISSUE TITLE
Chalk import error in the ts template

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo#14]
#### Bug description
Importing and using chalk in the ts template gives the following error:

````
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/mac/dev/collabo/nmgo-ts-api/node_modules/chalk/source/index.js from /Users/mac/dev/collabo/nmgo-ts-api/src/server.atlas.ts not supported.
Instead change the require of index.js in /Users/mac/dev/collabo/nmgo-ts-api/src/server.atlas.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.nodeDevHook [as .js] (/Users/mac/dev/collabo/nmgo-ts-api/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/Users/mac/dev/collabo/nmgo-ts-api/src/server.atlas.ts:17:33)
    at Module._compile (/Users/mac/dev/collabo/nmgo-ts-api/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/private/var/folders/rs/dmjbq_c945l5ym6hx5sxyy5r0000gn/T/ts-node-dev-hook-3677414275108084.js:69:33)
    at require.extensions.<computed> (/private/var/folders/rs/dmjbq_c945l5ym6hx5sxyy5r0000gn/T/ts-node-dev-hook-3677414275108084.js:71:20)
    at Object.nodeDevHook [as .ts] (/Users/mac/dev/collabo/nmgo-ts-api/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/Users/mac/dev/collabo/nmgo-ts-api/node_modules/ts-node-dev/lib/wrap.js:104:1)
    at Module._compile (/Users/mac/dev/collabo/nmgo-ts-api/node_modules/source-map-support/source-map-support.js:568:25)
[ERROR] 02:34:03 Error: require() of ES Module /Users/mac/dev/collabo/nmgo-ts-api/node_modules/chalk/source/index.js from /Users/mac/dev/collabo/nmgo-ts-api/src/server.atlas.ts not supported.
Instead change the require of index.js in /Users/mac/dev/collabo/nmgo-ts-api/src/server.atlas.ts to a dynamic import() which is available in all CommonJS modules.

````

#### Steps to reproduce the buggy behaviour
1. Go to https://github.com/code-collabo/node-mongo-api-boilerplate-templates
2. cd into the ts template and follow the instructions on the readme to install and run the project
3. Import chalk somewhere at the top of the db.connect.ts or db.atlas.connect.ts file:
````
import chalk from 'chalk';
````
4. Replace the console.log message inside the try block with:
````
console.log(chalk.green(`Whatever string that you met there`));
````
5. Replace the console.log message inside the catch block with:
````
console.log(chalk.red(`Whatever string that you met there`));
````

#### Expected behavior
There should not be an error. The color of the string produced by the try block should be green in the terminal, while the color of the string produced by the catch block should be red.

#### Screenshots
None

#### Additional context
None

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] There is no more error in the terminal because chalk is imported
- [ ] In the terminal, the color of the string produced by the try block is green
- [ ] In the terminal, the color of the string produced by the catch block is green
- [ ] I certify that I ran my checklist

**Comment by oyenuga17** [comment]
Please assign me

**Comment by Ifycode** [comment]
Thanks. Assigned to you @oyenuga17 👍🏽

**Comment by Ifycode** [comment]
Hi @oyenuga17. 
This is part of v1.0.0 fixes that we want to release in the coming week.

Any update on this issue?

**Comment by oyenuga17** [comment]
Good afternoon.. please I am having issue running npm run dev in my ts folder
<img width="1322" alt="Screenshot 2023-04-22 at 14 42 42" src="https://user-images.githubusercontent.com/64274826/233788490-0fcde82d-d7e7-46e4-8140-919fd45b4c7d.png">

**Comment by Ifycode** [comment]
You can see there that it says "Server running at undefined", it also said something about your connection string...

Do you know how to use or set up MongoDB locally? If not, follow this instruction:
- Rename `.example.env` file to `.env`. This is where we store secrets that we don't won't people to access publicly.
- Let's use atlas instead. In the .env file, You will see `MONGODB_ATLAS_URI=`, paste the string below after the = sign (add no space). I created this test atlas string one time, you can use it:
````
mongodb+srv://Mary:nodeMongoPassWord@cli-test-cluster.je7f6.mongodb.net/nodeMongoDB?retryWrites=true&w=majority
````
- In the place where you have `PORT=`, Add any port of your choice e.g. `PORT=4000`
- Use the same Port number in the `API_HOST_URL=` e.g. `API_HOST_URL=http://localhost:4000`

That's all. Let me know if you still are not able to run it @oyenuga17

**Comment by oyenuga17** [comment]
Okay i will do this

**Comment by Ifycode** [comment]
Any updates on this task? @oyenuga17

**Comment by oyenuga17** [comment]
No, i am just checking it right now, i fell really ill

**Comment by oyenuga17** [comment]
![image](https://user-images.githubusercontent.com/64274826/234432312-ecaeab44-e2c3-4ae7-8d97-90173f04573a.png)

This what i have...

**Comment by Ifycode** [comment]
Oh, so sorry @oyenuga17 Take care of yourself. I wish you a quick recovery. Would you like someone else to take up this issue?
> When you feel better and still wish to contribute there will be other issues that you can pick from.

**Comment by Ifycode** [comment]
Reassigning it to you @Dkingofcode, please help @oyenuga17 complete this issue.

**Comment by Dkingofcode** [comment]
Will do that

**Comment by oyenuga17** [comment]
I wanted to continue but it's being re-assigned no problem

**Comment by Ifycode** [comment]
You are still part of the assignees @oyenuga17 
I think I used the wrong word "reassigning" earlier, which caused some confusion. Sorry about this.
If you check the assignees for this issue, you will see I didn't unassign you.
I just added another assignee.

So you both can still collaborate or work together on this issue. 
I just didn't want to stress you since it's an urgent issue, and you said you fell ill.

If you still want to take up this issue alone, I can unassign @Dkingofcode 

Let me know what you decide 👍🏽

**Comment by Ifycode** [comment]
I also wanted to drop this here you can join the public community chat so that communication is smoother @oyenuga17 
Link to Code Collabo community chat on Gitter: https://matrix.to/#/#code-collabo-foss-community:gitter.im

I'm also awaiting your response to my previous message.

**Comment by oyenuga17** [comment]
> You are still part of the assignees @oyenuga17 I think I used the wrong word "reassigning" earlier, which caused some confusion. Sorry about this. If you check the assignees for this issue, you will see I didn't unassign you. I just added another assignee.
> 
> So you both can still collaborate or work together on this issue. I just didn't want to stress you since it's an urgent issue, and you said you fell ill.
> 
> If you still want to take up this issue alone, I can unassign @Dkingofcode
> 
> Let me know what you decide 👍🏽

Alright we can do it together

**Comment by Ifycode** [comment]
Great. Thank you @oyenuga17
