### ISSUE TITLE
Create an "API user error report" issue template for users that encounter errors that prevent them from using the API boilerplate template

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo#31]
#### Suggested improvement
Create an "API user error report" issue template in the **node-mongo-cli** repo where the API boilerplate templates could send users if an error occurs that prevents them from being able to use the API boilerplate template altogether.

#### Example of what we want to achieve after this improvement has been added
- Go to https://github.com/code-collabo/node-mongo-cli
- Click the issues tab, then click on new issue button to create a new issue
- Click on the get started button for the "CLI user error report" template (this is will give you an idea of how an issue template works in general).

#### Additional context
To implement it, take a clue from the CLI repo's .github folder: https://github.com/code-collabo/node-mongo-cli/tree/develop/.github

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] API user error report has been added to the node-mongo-cli repo
- [ ] I certify that I ran my checklist

**Comment by Dkingofcode** [comment]
@Ifycode Can i work on this issue?

**Comment by Ifycode** [comment]
Yes 👍🏼
Thank you for the PR
