### ISSUE TITLE
Help CLI user know where to report errors and that manual download options for API templates exist if they encounter error while using the CLI

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo#32]
#### Suggested improvement
Help CLI users know where to report errors, and that manual download options for API templates exist if they encounter errors while using the CLI.

#### Additional context
When there is an error in the terminal because the CLI cannot run on the user's OS or computer, alongside the error displayed to the user, let the user also know:
- That they can report the error they encountered at https://github.com/code-collabo/node-mongo-cli/issues/new?assignees=&labels=bug&template=cli-user-error-report.md
- That there is a manual download option for the API boilerplate templates at: https://github.com/code-collabo/node-mongo-api-boilerplate-templates

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] Where they can report the error is included in the error message displayed to the user
- [ ] Where they can find the manual download option for the API boilerplate template is included in the error message displayed to the user
- [ ] I certify that I ran my checklist

**Comment by Dkingofcode** [comment]
I would like to work on this issue

**Comment by Ifycode** [comment]
Good challenge 💪🏽👍🏼💯 for you.
I left you a review on the PR @Dkingofcode
