### ISSUE TITLE
Generate/create ISC license files for the templates that the CLI generates for users

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo#33]
#### Suggested improvement
Generate/create ISC license files for the templates that the CLI emits/generates for users.

#### Additional context
- This is the ISC license content to use: https://github.com/code-collabo/node-mongo-api-boilerplate-templates/blob/develop/LICENSE
- How to implement it? Take a clue from how the .gitIgnore file and .env files are created or generated in the main.js file: https://github.com/code-collabo/node-mongo-cli/blob/develop/src/main.js

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] The CLI now generates ISC license for the 3 API templates it generates
- [ ] The ISC license file content added is correct
- [ ] I certify that I ran my checklist

**Comment by Dkingofcode** [comment]
@Ifycode  would like to work on this issue.
