### ISSUE TITLE
The .env/.env.example files generated by the CLI still use old content

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo#34]
#### Issue description
The content of our .env.example files in the API template repo has been changed. But the .env/.env.example files generated by the CLI still use old content and do not use the new content yet. Update the content of the .env files generated by the CLI to match the ones in the repo containing the manual download option.

#### Additional context
- The main.js is likely where you need to make the change: https://github.com/code-collabo/node-mongo-cli/blob/develop/src/main.js
- Get the updated content from the API repo: https://github.com/code-collabo/node-mongo-api-boilerplate-templates

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] The content of the.env files generated by the CLI is the same as the one found in the API repo
- [ ] I certify that I ran my checklist

**Comment by Dkingofcode** [comment]
@Ifycode  i would like to work on this issue.
