### ISSUE TITLE
Add basic/temporary API documentation (i.e. API design and API call requests and responses) to API templates repo readme

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo#35]
#### Suggested improvement
Just before the **Documentation** section on the readme of the API boilerplate templates repo, add basic/temporary API documentation for working with the **/demo** endpoints that comes built-in with the API.

#### Describe the issue associated with the absence of this improvement
- For example, a number of us have assumed that the shape of the request body for the PATCH request, is the same as that of the POST and PUT request, but this is not so. It is possible that some users have concluded that the PATCH request is not working (that is if they are beginners and we want it to be beginner friendly).
- Also we are supposed to have a real API documentation like Swagger or Postman, but we have a lot of projects and it may take us a while before we are able to build it. The temporary API provided in the readme should help show people how to use it for now instead of having to wait till forever before they can see a doc on how to use the API.

#### Example of what we want to achieve after this improvement has been added
 The [buuks-express-api](https://github.com/Ifycode/buuks-express-api) repo contains an example of what we want to achieve. The 2 sections to look at are: the **API design** and **Request body and (successful) response** sections of the readme.

#### Modifications
- The **API design** title is fine, but in our own API design table, we don't want to add the Auth column, since we don't have authentication yet.
- We don't want our own title to be **Request body and (successful) response**. Instead, use **API call requests and responses** as the title of the 2nd section.
- If you click on any of the GET request dropdowns, you will see that under the Request body, they wrote "No response body". It should be "No request body". Correct this for our own repo.

#### Additional context
Use the same formatting, headers, tables, dropdowns, code blocks etc as what you see in the buuks repo example.

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] The readme of the API boilerplates repo now contains the temporary documentation API design and API call requests and responses
- [ ] The temporary API doc is added just before the **Documentation** section of the API boilerplates repo's readme
- [ ] The temporary API doc is written accordingly and correctly for all methods (GET, POST etc) and the /demo (and demo id) endpoints that exist in the API
- [ ]  The same formatting, headers, tables, dropdowns, code blocks etc from the buuks repo example is used
- [ ] I certify that I ran my checklist

**Comment by Dkingofcode** [comment]
@Ifycode  I would like to work on this issue.

**Comment by Ifycode** [comment]
@Dkingofcode I'm un assigning you from this issue. Complete this other task first: https://github.com/code-collabo/node-mongo/issues/32

I left you a note in the PR submitted for that task.

**Comment by Ifycode** [comment]
> **Note**
>
> Anyone is allowed to take up fixing this issue is @Dkingofcode has not been reassigned to this issue

cc: @code-collabo/intern

**Comment by Dkingofcode** [comment]
Ok, Noted
