### ISSUE TITLE
Write js script to remove automatically generated folders in the node-mongo CLI during development

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/node-mongo#42]
#### Suggested improvement
During development i.e. while fixing issues or adding features to the [node-mongo CLI codebase](https://github.com/code-collabo/node-mongo-cli), you would definitely need to run the node-mongo command at one point or the other. This will Automatically generate folder(s). 

#### Describe issue associated with the absence of this improvement
- Manually looking for and deleting those folders generated is tedious, especially if you created so many.
- Contributors could push the generated folders to github by mistake.

#### Steps to reproduce issue associated with the absence of this improvement
1. Go to the [node-mongo CLI codebase](https://github.com/code-collabo/node-mongo-cli)
2. Follow the instructions in the [node-mongo contributor guide](https://code-collabo.gitbook.io/node-mongo-v2.3.0/contribution-guide/node-mongo) to install and set up the CLI on your computer in preparation for development
3. Run the `node-mongo` command or follow the [CLI usage](https://code-collabo.gitbook.io/node-mongo-v2.3.0/#cli-usage) instructions in the doc to generate as many folders you like
4. Try looking for all the folders you generated and try to delete them all

#### Improvement details
- Create a file called **cleanup.js** in the root of the CLI repo.
- Write a script inside this file that deletes the automatically generated folders by the CLI (only).
- Add it to the script section of the package.json file. So that when you run **npm run cleanup** the cleanup script is executed.

#### Screenshot (example)
None

#### Modifications
None

#### Additional context
None

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] **cleanup.js** file exists in the root of the CLI repo containing scripts that deletes the automatically generated folders by the CLI (only)
- [ ] Running **npm run cleanup** executes the code inside of the cleanup file
- [ ] I certify that I ran my checklist

**Comment by oyenuga17** [comment]
@Ifycode please assign me

**Comment by Ifycode** [comment]
Hi @oyenuga17 
You picked a good/challenging one. Assigned to you!
Let me know if you need any help with this (in the community).

**Comment by Ifycode** [comment]
@oyenuga17

**Comment by Ifycode** [comment]
@oyenuga17 help comment on this issue.
