### ISSUE TITLE
[TS Revamp]Setup typescript and tsconfig file

### ISSUE THREAD

**Issue by tylerjusfly** [code-collabo/node-mongo#60]
**Description**
 We want to start migrating this project to typescript. so the first thing is to install typescript and any other packages needed for typescript to run.

We will also set up the typescript configuration file.

1. Install typescript
2. create tsconfig file for typescript configuration

> Note: after installation and setting up of tsconfig , typescript needs a .ts file to compile successfully.

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.

- [ ] Ts config file have been added
- [ ] Typescript has been installed
- [ ] all code works as before
- [ ] I certify that I ran my checklist

**Comment by samuko-things** [comment]
@tylerjusfly you have been assigned to this issue as requested. good luck
